spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    tomcat:
      max-active: 10
      max-idle: 10000
      max-wait: 10000
      test-on-borrow: true
    url: jdbc:h2:file:${dataBaseUrl}
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver
  redis:
    host: 192.168.119.90
    port: 6379
    lettuce.pool:
      max-active: 5
      max-idle: 1
      min-idle: 1
      max-wait: 5000
    timeout: 10000

dataBaseUrl: ./h2/alerts_db;DB_CLOSE_ON_EXIT=FALSE


initialDelay: 10000
fixedDelay: 60000

server:
  tomcat:
    accessLog.enabled: true
    basedir: "${LOG_PATH}/Application"
    accessLogPattern: "%h %l %u %t \"%r\" %s %b %D"


